# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

use_frameworks!
target 'CastAnything' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  
  pod 'google-cast-sdk' , '>=3.2.0'
  
  # Pods for CastAnything
end
